on: push
name: Documentation Generation Workflow
jobs:
  docFX-GenerateDocumentation:
    name: DocFX - Generate TypeScript Documentation
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: DocFX - Build and publish documentation
      run:
        choco install docfx -y
        docfx docfx_projectdocfx.json
      shell: pwsh
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
