on: push
name: Documentation Generation Workflow
jobs:
  docFX-GenerateDocumentation:
    name: DocFX - Generate TypeScript Documentation
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: DocFX - Build documentation
      run: |
        bash ./actions/build.sh
      shell: pwsh
    - name: DocFX - Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      run: |
        bash ./actions/commit.sh
    - name: DocFX - Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        bash ./actions/push.sh
    - name: DocFX - Deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
        SCRIPT_MODE: true
      run: |
        curl -X POST https://api.github.com/repos/carolinesena/carolinesena.github.io/Docfx/pages/builds
