on: push
name: Documentation Generation Workflow
jobs:
  docFX-GenerateDocumentation:
    name: DocFX - Generate TypeScript Documentation
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: DocFX - Build documentation
      run: |
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
        apt update
        apt install mono-complete --yes
        wget https://github.com/dotnet/docfx/releases/download/v2.39.1/docfx.zip
        unzip docfx.zip -d _docfx
        cd docfx_project
        mono ../_docfx/docfx.exe
        cd ..
      shell: bash
    - name: publish documentation
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USER: ${{ secrets.GH_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git init
        git config --global user.email caroline.sena@traycorp.com.br
        git config --global user.name carolinesena
        git add . --force
        git status
        git commit -m "Update auto-generated documentation."
        git push --set-upstream https://github.com/carolinesena/Docfx.git master
