on: push
name: Documentation Generation Workflow
jobs:
  docFX-GenerateDocumentation:
    name: DocFX - Generate TypeScript Documentation
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: DocFX - Build documentation
      run: |
        choco install docfx -y
        docfx docfx_project/docfx.json
      shell: pwsh
  docFX-PublishDocumentation:
    runs-on: ubuntu-18.04
    steps:
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
