on: push
name: Documentation Generation Workflow
jobs:
  docFX-GenerateDocumentation:
    name: DocFX - Generate TypeScript Documentation
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: DocFX - Build documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      run: |
        sudo wget https://github.com/dotnet/docfx/releases/download/v2.39.1/docfx.zip
        sudo unzip docfx.zip -d _docfx
        cd docfx_project
        rm -rf obj/.cache/build/
        mono ../_docfx/docfx.exe
        cd ..
        sudo rm -rf _docfx
        sudo rm -f docfx.zip
      shell: pwsh
    - name: DocFX - Commit
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USER: ${{ secrets.GH_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      run: |
        bash ./actions/push/entrypoint.sh
    - name: DocFX - Push
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      run:
        bash ./actions/push.sh
    - name: Deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: .
        SCRIPT_MODE: true
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
        bash ./entrypoint.sh
