on: push
name: Documentation Generation Workflow
jobs:
  docFX-GenerateDocumentation:
    name: DocFX - Generate TypeScript Documentation
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: DocFX - Build documentation
      run: |
        sudo wget https://github.com/dotnet/docfx/releases/download/v2.39.1/docfx.zip
        sudo unzip docfx.zip -d _docfx
        cd docfx_project
        rm -rf obj/.cache/build/
        mono ../_docfx/docfx.exe
        cd ..
      shell: pwsh
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
