on: push
name: Documentation Generation Workflow
jobs:
  docFX-GenerateDocumentation:
    name: DocFX - Generate TypeScript Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: DocFX - Build and publish documentation
      uses: ./actions/docprep
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USER: ${{ secrets.GH_USER }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs



